// export const avatars = [
//   { id: 1, pic: "bhr", name: "RezaBhm" },
//   { id: 2, pic: "emad", name: " EmadAraban" },
//   { id: 3, pic: "farzi", name: "RezaFrz" },
//   { id: 4, pic: "mamad", name: "mohammadvlt" },
//   { id: 5, pic: "amir", name: " AmirHbb" },
//   { id: 6, pic: "mac", name: "mac" },
// ];

export const avatars = [
  {
    id: 1,
    job: "فول استک",
    name: "رضا بهرامی",
    telegram: "",
    linkdien: "",
    github: "",
    year: "6 سال",
    location: "",
    email: "",
    pic: "bhr",
  },

  {
    id: 2,
    job: "فول استک",
    name: " عماد عربان",
    telegram: "",
    linkdien: "",
    github: "",
    year: "3 سال",
    location: "",
    email: "arabanemad@gmail.com",
    pic: "emad",
  },
  {
    id: 3,
    job: "فول استک",
    name: "رضا فرضی پور",
    telegram: "",
    linkdien: "",
    github: "",
    year: "3 سال",
    location: "",
    email: "farzipour_reza@yahoo.com",
    pic: "farzi",
  },
  {
    id: 4,
    job: "بک اند",
    name: "محمدرضا ولایتی",
    telegram: "",
    linkdien: "",
    github: "",
    year: "1.5 سال",
    location: "",
    email: "mohammadrv2003@gmail.com",
    pic: "mamad",
  },
  {
    id: 5,
    job: "فرانت اند",
    name: " امیرحسین حبیبی",
    telegram: "",
    linkdien: "",
    github: "",
    year: "3 سال",
    location: "",
    email: "ahossein960@gmail.com",
    pic: "amir",
  },
  {
    id: 6,
    job: "سئو,دیجیتال مارکیتنگ",
    name: "مهدی خضری",
    telegram: "",
    linkdien: "",
    github: "",
    year: "2 سال",
    location: "",
    email: "",
    pic: "mac",
  },
];
export const initialCv2 = [
  { id: 1, about: "bhr", skills: "RezaBhm" },
  { id: 2, about: "mac", skills: "mac" },
  { id: 3, about: "farzi", skills: "RezaFrz" },
  { id: 4, about: "mamad", skills: "mohammadvlt" },
  { id: 5, about: "amir", skills: " AmirHbb" },
  { id: 6, about: "emad", skills: " EmadAraban" },
];
